# Generated by Django 4.2.7 on 2023-11-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=30)),
                ('timestamp_utc', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=30)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time_local', models.CharField(max_length=16)),
                ('end_time_local', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=32)),
            ],
        ),
    ]
